### ISSUE TITLE
Cleanup Project from problems

### ISSUE THREAD

**Issue by YuriyTigiev** [vicky-gonsalves/deno_rest#16]
How to correctly fix these problems?

![image](https://user-images.githubusercontent.com/22752322/100382956-e9de6c00-3035-11eb-875a-868e9cd5254e.png)

**Comment by vicky-gonsalves** [comment]
I don't know.. Let's skip that for now.

**Comment by 1antares1** [comment]
Maybe this could solve the problem, @vicky-gonsalves ?
https://github.com/denoland/deno/issues/5027#issuecomment-715631132
