### ISSUE TITLE
TypeError: crypto.subtle.importKey is not a function

### ISSUE THREAD

**Issue by KotadiyaHiral** [vicky-gonsalves/deno_rest#21]
After updating, Deno v1.11.0 I am getting typeError in encryption.

const aes = new AES(this.key, { mode: "cbc", iv: this.salt }); // This works proper
const cipher = await aes.encrypt(str); // Error genrates from here.

Error is:
TypeError: crypto.subtle.importKey is not a function at WebCryptoAES.loadKey (https://deno.land/x/god_crypto@v1.4.9/src/aes/aes_wc.ts:24:39) at WebCryptoAES.encrypt (https://deno.land/x/god_crypto@v1.4.9/src/aes/aes_wc.ts:37:28) at AES.encrypt (https://deno.land/x/god_crypto@v1.4.9/src/aes/mod.ts:40:43)

**Comment by vicky-gonsalves** [comment]
Will check this soon

**Comment by KotadiyaHiral** [comment]
Thank you for your support. The issue is resolved by god_crypto.
