### ISSUE TITLE
password encryption

### ISSUE THREAD

**Issue by thepapanoob** [vicky-gonsalves/deno_rest#24]
Hi,

i noticed that youre encrypting passwords using AES. 
That is a really, really bad idea. One should only hash passwords.

Use argon2 or bcrypt to actually hash the password (with an salt)

**Comment by vicky-gonsalves** [comment]
yes you are right. I just wanted to demonstrate the usecase here. I am working on next update to get rid of godcrypto too. If you like you can contribute too
