### ISSUE TITLE
denon start 

### ISSUE THREAD

**Issue by YuriyTigiev** [vicky-gonsalves/deno_rest#3]
Hello, 

Looks like something is missing. 

PS C:\Users\yuriy\OneDrive\Documents\GitHub\deno_rest> denon start
denon : The term 'denon' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ denon start
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (denon:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by vicky-gonsalves** [comment]
@YuriyTigiev I think you have not installed denon in your machine or maybe something wrong with the installed package. Please go through denon's official guide for installation. 

https://deno.land/x/denon
