### ISSUE TITLE
TODO: Document and Schema Version Controls and Logging of changes for Audit

### ISSUE THREAD

**Issue by YuriyTigiev** [vicky-gonsalves/deno_rest#7]
If is it possible could you also add in the TODO List the following two points
1) Document and Schema Version Controls (history of changes)
2) Logging of changes for Audit (who, when, and what changed in the document)

You have a good project with best practice for learning Deno from scratch

**Comment by vicky-gonsalves** [comment]
Yes @YuriyTigiev This looks a very good practice, I'll add in TODO.

**Comment by YuriyTigiev** [comment]
I have done the first step - update the function createUser.
Deno driver doesn't support multi-document and I'm not sure if this implementation is optimal for my case.

```
  public static async createUser(
    options: CreateUserStructure,
  ): Promise<ObjectId | Error> {
    const { name, email, password, role, isDisabled } = options;
    const hashedPassword = await HashHelper.encrypt(password);
    const createdAt = new Date();

    const user: ObjectId = await User.insertOne(
      { name, email, password: hashedPassword, role, isDisabled, createdAt, doc_version: 1},
    );

    if(user){
      const user_history: ObjectId = await UserHistory.insertOne(
        {_id:user,  name, email, password: hashedPassword, role, isDisabled, createdAt, doc_version: 1},
      );
    }
    else {
      log.error("Could not create user");
      return throwError({
        status: Status.BadRequest,
        name: "BadRequest",
        path: "user",
        param: "user",
        message: `Could not create user`,
        type: "BadRequest",
      });
    }
    return user;
  }
```

**Comment by vicky-gonsalves** [comment]
@YuriyTigiev Looks good to me. Would you mind opening a pull request?

**Comment by YuriyTigiev** [comment]
> Looks good to me. Would you mind opening a pull request?

Pull or push? 

You don't have permissions to push to 'vicky-gonsalves/deno_rest' on GitHub. Would you like to create a fork and push to it instead?

I can send you changes (3 files) by email.  I

**Comment by vicky-gonsalves** [comment]
Hi @YuriyTigiev ,
Let's follow the best practice here so that in future other devs can also see the changes.

Fork master branch into your git account -> make changes-> push commits to your master branch-> open Pull request to this master branch. 
Once you open the pull request, I ll review the changes and merge into master branch

**Comment by YuriyTigiev** [comment]
I will do it
but now  deno cache --reload --unstable --lock-write --lock=lock.json ./deps.ts returns an error 
error: Import 'https://deno.land/x/djwt@v1.9/validate.ts' failed: 404 Not Found

**Comment by vicky-gonsalves** [comment]
@YuriyTigiev It seems there is some issue with the djwt library. Meanwhile, you can use repository version directly untill developers solve the issue.

https://raw.githubusercontent.com/timonson/djwt/master/mod.ts

**Comment by YuriyTigiev** [comment]
Now I'm getting  another error 

```
import * as yup from "https://cdn.skypack.dev/yup";

export {
  AES,
  encode,
} from "https://deno.land/x/god_crypto/mod.ts";
export {
  Application,
  Router,
  send,
  Context,
  Status,
  isHttpError,
  helpers,
} from "https://deno.land/x/oak/mod.ts";
export type {
  RouterContext,
} from "https://deno.land/x/oak/mod.ts";
export { config as dotEnv } from "https://deno.land/x/dotenv/mod.ts";
export {
  handlers,
  getLogger,
  setup,
} from "https://deno.land/std/log/mod.ts";
export { MongoClient, ObjectId } from "https://deno.land/x/mongo/mod.ts";
export { oakCors } from "https://raw.githubusercontent.com/tajpouria/cors/master/mod.ts"; // Currently using fork version to support deno 1.4.0
export { validateJwt } from "https://raw.githubusercontent.com/timonson/djwt/master/mod.ts";
export type {
  Jose,
  Payload,
} from "https://raw.githubusercontent.com/timonson/djwt/master/mod.ts";
export {
  makeJwt,
  setExpiration,
} from "https://raw.githubusercontent.com/timonson/djwt/master/mod.ts";
export { yup };

```

```

Check file:///C:/Users/yuriy/OneDrive/Documents/GitHub/deno_rest/deps.ts
error: TS2305 [ERROR]: Module '"https://deno.land/x/djwt@v1.9/mod.ts"' has no exported member 'validateJwt'.
export { validateJwt } from "https://deno.land/x/djwt@v1.9/mod.ts";
         ~~~~~~~~~~~
    at file:///C:/Users/yuriy/OneDrive/Documents/GitHub/deno_rest/deps.ts:27:10

TS2305 [ERROR]: Module '"https://deno.land/x/djwt@v1.9/mod.ts"' has no exported member 'Jose'.
  Jose,
  ~~~~
    at file:///C:/Users/yuriy/OneDrive/Documents/GitHub/deno_rest/deps.ts:29:3

TS2305 [ERROR]: Module '"https://deno.land/x/djwt@v1.9/mod.ts"' has no exported member 'makeJwt'.
  makeJwt,
  ~~~~~~~
    at file:///C:/Users/yuriy/OneDrive/Documents/GitHub/deno_rest/deps.ts:33:3

TS2305 [ERROR]: Module '"https://deno.land/x/djwt@v1.9/mod.ts"' has no exported member 'setExpiration'.
  setExpiration,
  ~~~~~~~~~~~~~
    at file:///C:/Users/yuriy/OneDrive/Documents/GitHub/deno_rest/deps.ts:34:3

Found 4 errors.


```

**Comment by vicky-gonsalves** [comment]
Try deleting `lock.json` file and reloading the deps. It may solve the issue

**Comment by YuriyTigiev** [comment]
The same result

**Comment by vicky-gonsalves** [comment]
From the error stack, I don't know why but for some reason in your dependencies it still looking for https://deno.land/x/djwt@v1.9/mod.ts
It should be pointing to https://raw.githubusercontent.com/timonson/djwt/master/mod.ts

**Comment by YuriyTigiev** [comment]
```
Check file:///C:/Users/yuriy/OneDrive/Documents/GitHub/deno_rest/deps.ts
error: TS2305 [ERROR]: Module '"https://raw.githubusercontent.com/timonson/djwt/master/mod.ts"' has no exported member 'validateJwt'.
export { validateJwt } from "https://raw.githubusercontent.com/timonson/djwt/master/mod.ts";
         ~~~~~~~~~~~
    at file:///C:/Users/yuriy/OneDrive/Documents/GitHub/deno_rest/deps.ts:27:10

TS2305 [ERROR]: Module '"https://raw.githubusercontent.com/timonson/djwt/master/mod.ts"' has no exported member 'Jose'.
  Jose,
  ~~~~
    at file:///C:/Users/yuriy/OneDrive/Documents/GitHub/deno_rest/deps.ts:29:3

TS2305 [ERROR]: Module '"https://raw.githubusercontent.com/timonson/djwt/master/mod.ts"' has no exported member 'makeJwt'.
  makeJwt,
  ~~~~~~~
    at file:///C:/Users/yuriy/OneDrive/Documents/GitHub/deno_rest/deps.ts:33:3

TS2305 [ERROR]: Module '"https://raw.githubusercontent.com/timonson/djwt/master/mod.ts"' has no exported member 'setExpiration'.
  setExpiration,
  ~~~~~~~~~~~~~
    at file:///C:/Users/yuriy/OneDrive/Documents/GitHub/deno_rest/deps.ts:34:3

Found 4 errors.
PS C:\Users\yuriy\OneDrive\Documents\GitHub\deno_rest>

```

**Comment by vicky-gonsalves** [comment]
@YuriyTigiev It looks like https://deno.land/x/djwt@v1.9/mod.ts ia back to life. Could you possibly revwrt back and check its working?

**Comment by YuriyTigiev** [comment]
I think we should wait for 1-2 days. 

Download https://deno.land/x/oak@v6.3.1/mediaTyper.ts
Download https://deno.land/std@0.73.0/async/mod.ts
error: Import 'https://deno.land/x/djwt@v1.9/create.ts' failed: 404 Not Found
    at file:///C:/Users/yuriy/OneDrive/Documents/GitHub/deno_rest/deps.ts:28:0
PS C:\Users\yuriy\OneDrive\Documents\GitHub\deno_rest>

**Comment by vicky-gonsalves** [comment]
Yes I believe they are working on it. Let's wait.

**Comment by YuriyTigiev** [comment]
https://github.com/timonson/djwt/issues/38#issuecomment-723205372

**Comment by vicky-gonsalves** [comment]
@YuriyTigiev Thanks for commenting. I am fixing those breaking changes for djwt

**Comment by vicky-gonsalves** [comment]
40114edf9b72a2090ec83e46bb56ee26bc723d64 
This fixes the issue of djwt 
@YuriyTigiev Please check this commit.
I have also added support for Deno v1.5.1 and fixed some lint and code format in following commit
da3f980c46c7c6fd300d63657f593f88ee1bfe27

**Comment by vicky-gonsalves** [comment]
> If is it possible could you also add in the TODO List the following two points
> 
> 1. Document and Schema Version Controls (history of changes)
> 2. Logging of changes for Audit (who, when, and what changed in the document)
> 
> You have a good project with best practice for learning Deno from scratch

#9

**Comment by YuriyTigiev** [comment]
I have checked. Everything works
